Repository the-hideout/stash, pull requests merged in 2022-06, with the labels that each got.

#40 Use PK RUB sell price
  commands/price.mjs
Labels: bug

#46 Streamline queries
  commands/barter.mjs
  commands/craft.mjs
  commands/price.mjs
  modules/get-crafts-barters.mjs
  modules/get-crafts.mjs
  modules/get-items.mjs
Labels: enhancement

#60 updates commands on the readme
  README.md
Labels: documentation

#62 `/changes` command
  README.md
  commands/changes.mjs
Labels: enhancement
